"""empty message

Revision ID: 62117eab043f
Revises: fb83984995d7
Create Date: 2020-06-04 17:08:40.185142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62117eab043f'
down_revision = 'fb83984995d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('project_project_name_key', 'project', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('project_project_name_key', 'project', ['project_name'])
    # ### end Alembic commands ###
