"""empty message

Revision ID: ae7443e2daf4
Revises: c182462926ab
Create Date: 2020-06-04 17:36:22.249982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae7443e2daf4'
down_revision = 'c182462926ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('task_sub_task_name_key', 'task', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('task_sub_task_name_key', 'task', ['sub_task_name'])
    # ### end Alembic commands ###
