"""empty message

Revision ID: c182462926ab
Revises: 62117eab043f
Create Date: 2020-06-04 17:28:01.276432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c182462926ab'
down_revision = '62117eab043f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('task_task_name_key', 'task', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('task_task_name_key', 'task', ['task_name'])
    # ### end Alembic commands ###
